name: test

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --depth=1 third_party/httplib third_party/json third_party/spdlog

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17.0.1"

      - run: |
          cmake -S . -B build -DCPJVIEW_ENABLE_TEST=on -DCPJVIEW_GLOBAL_LLVM=on -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - run: |
          cmake --build build

      - run: |
          ctest --build-config ${{ matrix.build_type }}
        working-directory: build
